data:
    path: data/datasets/sr_dataset_test_benchmark
    mode: time # events/time
    window: 0.005 # events/time
    passes_loss: 5
    cache: False

loader:
    batch_size: 1
    resolution: [180, 180] # H x W
    augment: []
    gpu: 0

distortion:
    undistort: True
    fx: 208.2445
    fy: 208.3810
    xc: 90.0
    yc: 90.0
    dist_coeff: [-0.4344, 0.1873, 0.0, 0.0, 0.0] # k1, k2, p1, p2, p3, p4

vis:
    enabled: False
    px: 400
    bars: True
    store: False
    activity: False
    ground_truth: True
